
import './globals.scss'
import Header from './components/common/Header';
import StyledComponentsRegistry from './lib/registry';


export const metadata = {
  title: "Ayaan Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className=''>
        <StyledComponentsRegistry>
          <Header />
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
